### Vectorization


In [ ]:
import numpy as np
a = np.array([i for i in range(20)])
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)


tic = time.time()
# Vectorized version
c = np.dot(a,b)
toc = time.time()

print(c)
print((toc-tic)*1000)

# Non vectorized version
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] *b[i]
toc = time.time()
print(c)
print((toc-tic)*1000)

250127.78608949573
1.9600391387939453
250127.7860894935
399.9369144439697


In [2]:
# Calculate the exponential of the matrix using the numpy exp function.

import numpy as np
a = np.random.rand(1000000)
a_exp = np.exp(a)
a_exp

array([2.4666496 , 1.54678134, 1.15757677, ..., 2.60298933, 1.36114717,
       1.19044731])

### Broadcasting

In [ ]:
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104,2,8],[1.8,135,99.0,0.9]])

In [ ]:
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 105.4,  76.9])

In [ ]:
perc = 100*A/cal
perc

array([[94.91525424,  0.        ,  4.17457306, 88.42652796],
       [ 2.03389831, 43.51464435,  1.89753321, 10.40312094],
       [ 3.05084746, 56.48535565, 93.92789374,  1.17035111]])

In [ ]:
cal.reshape(1,4)

array([[ 59. , 239. , 105.4,  76.9]])

In [ ]:
cal + [[100],[200]] 

array([[159. , 339. , 205.4, 176.9],
       [259. , 439. , 305.4, 276.9]])

In [ ]:
a = np.random.randn(5)  # Never use like this. Rank 1 vector
print(a)
print(a.shape)

a_trns = np.dot(a,a.T)
print(a_trns)
print(a_trns.shape)

[ 1.25316076  0.64767138 -0.91410032  0.22881068 -0.12031207]
(5,)
2.8922988353610752
()


In [ ]:
a = np.random.randn(5,1)
print(a)
print(a.shape)

a_trns = np.dot(a,a.T)
print(a_trns)
print(a_trns.shape)

[[-1.09150065]
 [ 2.63819605]
 [-0.57393101]
 [-0.48771622]
 [-0.10189776]]
(5, 1)
[[ 1.19137366 -2.87959269  0.62644606  0.53234257  0.11122147]
 [-2.87959269  6.9600784  -1.51414251 -1.28669101 -0.26882626]
 [ 0.62644606 -1.51414251  0.3293968   0.27991546  0.05848228]
 [ 0.53234257 -1.28669101  0.27991546  0.23786711  0.04969719]
 [ 0.11122147 -0.26882626  0.05848228  0.04969719  0.01038315]]
(5, 5)


In [ ]:
a=np.random.randn(12288,150) 

# a.shape = (12288, 150)a.shape=(12288,150)

b = np.random.randn(150, 45)
b=np.random.randn(150,45) 

# b.shape = (150, 45)b.shape=(150,45)

c = np.dot(a,b)
c.shape

(12288, 45)

In [ ]:
a=np.array([[2,1],[1,3]])

np.dot(a,a)

array([[ 5,  5],
       [ 5, 10]])

In [ ]:
a = np.array( [[1,1],[1,-1]])
b = np.array([[2], [3]])
c = a + b
c

array([[3, 3],
       [4, 2]])

In [ ]:
x=np.array([[[1],[2]],[[3],[4]]])
x.shape

(2, 2, 1)

In [5]:
a=np.random.randn(3,3) # a.shape = (3, 3)a.shape=(3,3)

b=np.random.randn(3,1)

c = a * b
c.shape

(3, 3)

In [ ]:
a

array([ 0.19993033,  0.62827028, -0.94691059, -0.42035783,  2.05432594,
        0.55539085, -0.38189963,  1.5240871 , -1.74226591,  0.5492667 ])

In [ ]:
a.shape

(10,)